version: '3'
services:
  dynamodb:
    image: fingershock/dynamodb-local
    command: -dbPath /dynamodb_data -sharedDb
    ports:
      - "8000:8000"
  s3:
    image: minio/minio
    volumes:
      - ".local/s3_data:/export"
    ports:
      - "4567:9000"
    environment:
      MINIO_ACCESS_KEY: dummy
      MINIO_SECRET_KEY: dummydummy
    command: server /export
