name: test

on:
  push:
    branches: [ master ]
  pull_request:

env:
  GO_VERSION: 1.14.2

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - name: Check out code
      uses: actions/checkout@v2
    - name: Test
      run: |
        make init
        make test-coverage
    - name: Send Coverage to coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make send-coverage
    - name: Send Coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: gotest.cov
